version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: socialx-db
    environment:
      POSTGRES_DB: socialx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ranjith@123()
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: socialx-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/socialx
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ranjith@123()
      SERVER_PORT: 8085
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8085:8085"

  frontend:
    build:
      context: ./frontend
    container_name: socialx-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:

